# Generated by Django 4.1.1 on 2022-09-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_alter_libro_descripcion_alter_libro_imagen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
